[libraries]
firebase-database = { group = "com.google.firebase", name = "firebase-database", version.ref = "firebase-database" }
[plugins]
android-application = { id = "com.android.application", version = "8.4.2" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "1.9.24" }
google-services = { id = "com.google.gms.google-services", version = "4.4.2" }

[versions]
core-ktx = "1.13.1"
appcompat = "1.6.1"
firebase-database = "21.0.0"
